### ISSUE TITLE
cv2 import fails with `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`.

### ISSUE THREAD

**Issue by kenfus** [kenfus/ecallisto_timeseries_db#1]
```
(ecallisto_tsdb) vincenzo@v000792:~/ecallisto/ecallisto_timeseries_db$ python continiously_add_data_to_database.py --start_date 2023-03-01
Traceback (most recent call last):
  File "/home/vincenzo/ecallisto/ecallisto_timeseries_db/continiously_add_data_to_database.py", line 13, in <module>
    from database_utils import *
  File "/home/vincenzo/ecallisto/ecallisto_timeseries_db/database_utils.py", line 27, in <module>
    from spectogram_utils import masked_spectogram_to_array, spec_time_to_pd_datetime
  File "/home/vincenzo/ecallisto/ecallisto_timeseries_db/spectogram_utils.py", line 1, in <module>
    import cv2
  File "/home/vincenzo/miniconda3/envs/ecallisto_tsdb/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/vincenzo/miniconda3/envs/ecallisto_tsdb/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/vincenzo/miniconda3/envs/ecallisto_tsdb/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by kenfus** [comment]
Solution: No cv2 is used.
